#!/bin/bash

BINDIR=$(dirname "$(readlink -f $0)")
. $BINDIR/utils

log_info "Building source builder docker image."
docker build -t aws_onboarding_lambda_builder $BINDIR/docker
log_done "Finished building docker image"

log_info "Packaging lambdas code in dist/lambdas"
docker run  --rm \
            --mount type=bind,source="$SRCDIR/src",target=/tmp/src \
            --mount type=bind,source="$SRCDIR/requirements.txt",target=/tmp/requirements.txt \
            --mount type=bind,source="$BINDIR/dist",target=/tmp/output \
            -e ENVIRONMENT_LAMBDA_ZIP="aws_environment_setup.zip" \
            -e ONBOARDING_LAMBDA_ZIP="aws_ec2_auto_onboarding.zip" \
            aws_onboarding_lambda_builder
log_done "Finished packaging lambdas code"
